### ISSUE TITLE
Limit latitude at which spots can appear for stars that we are seeing from the equator

### ISSUE THREAD

**Issue by amunozj** [bmorris3/dot#33]
At least for the Sun, spot darkening and faculae brightening largely cancel at the limb, so I think it is reasonable to limit the latitudes when stars are nicely perpendicular like the one you showed.

**Comment by bmorris3** [comment]
Right now the implementation of `dot` imposes a 10 degree latitude-exclusion region near each pole, which serves two purposes: it avoids the coordinate singularity at the pole where the longitude becomes meaningless, and it limits us to be sensitive only to the spots that rotate into and out of view (true polar spots cause no rotational modulation). I haven't implemented faculae in any way yet, but that'd be a neat addition!
